version: "3.7"
services:
  # EVENT DISPATCHER SERVICE
  eventdispatcher:
    build: ./eventDispatcher
    volumes:
      - eventdispatcher_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  # DATABASE
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: claims_management_system
      MYSQL_USER: claims
      MYSQL_PASSWORD: claims123
  # OBJECT REPOSITORY SERVICE
  claimrepository:
    build: ./claimRepository
    ports:
      - "8081:8081"
    restart: always
    links: 
      - "db"
      - "eventdispatcher"
    environment: 
      HTTP_PORT: 8081
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: claims_management_system
      DB_USER: claims
      DB_PASS: claims123
      EVENT_DISPATCHER_HOST: amqp://eventdispatcher
      WAIT_TO_START: 0
      TZ: Asia/Singapore
  
  # CLAIM SUBMISSION SERVER
  claimsubmissionserver:
    build: ./claimSubmission/server
    ports:
      - "5000:5000"
    restart: always
    links: 
      - "claimrepository"
    environment: 
      HOST: 0.0.0.0
      PORT: 5000
      DIALOG_FLOW_PROJECT_ID: claimbot-vxtlgn
      DIALOG_FLOW_PRIVATE_KEY_ID: 89442cfc2499c57d9a67bc677ae436f36a2b8dc0
      DIALOG_FLOW_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC1hykhPh/zqGIy\nXsK1HhSPsVapRVTqYqFxXk28nTIGpsfiacXS2ls/8VHGBfQlcA+xyL6MONkW593A\nUWXJk87FGH/HUvHA1SR7DQ1IyfE82/pXn4C+RIfgXA4wX/GrylvY0AjxB+BNy9GV\nW4hxngMSH5r5INO5SaBIiFo0WvXqR9B3vwrKI8BNxKs93WK1RFingPcWLwNXViwI\nqKZCdvWb6tIVAdb4HrCn2JBd8wIl0U2GWUeDvFUhT3C3Lvi8oa6FFm4AuUYJ0khb\nBjlsEtjvudCLODqjBom7b5z8WdzNVVuAQHzkGg8WrcRdd1X4qkkxe7nH+WQD2Y0Q\nn6BL3yVTAgMBAAECggEAAjcUnm6WbiJAP/EnLt7cpbRXOb56NCdwZPPKJnBu031t\n3NzBne4/4GJUzT8UixRQ7RgQDOsYY0cZBPUieDQ6zkMnoSpdEd43OOpsmJ+Uhop6\neXdOONyM/SmAIZZfF4gsOjspYScGDD6CaMWh9eyYlSPSBehLnqYMPRQQ4hygPMw5\nWV0ftBzNuSrqFNksEWlus71qdbKqpqj6dUdWfl5YLVL9CGjsWSq48wr0qCtdVm/K\nVUGPOE116wN5Yq0mOUDHrfoPUFjNMvB1wK7ejRhGigXzP0n86xzBvAENNfn8M5AP\n8eeedrjEERfvTqM4udOZj6NH1zyDC6jyEt66JYMS7QKBgQDxSo/Lpb0FBbyd7ISw\nCC0WiKmYRyyzvozx/+8XnxJuiAovY78i4ZoysfGyP+fL70GOeesB9i+R4vvn5ROP\nL5oDw4SBj9aVu1F+tGWeAwHMJCAht9HrnJ7zCEfvl6VqjjyqhykZI51gZYRFVHQX\nklB/zaHMrYB3phjw4wrIcCgOhQKBgQDAl/iWFOl6dEDYIHMG1EXnXH/6kmCXj8JC\nyQFk/yWcynG9+sjOQxDQKlpqNvGxTb5NxRrLASv9a1nNG3fybUzgf0ze71nWOwZe\nuHfsrNbod4PnyfE2qEafB86wHtoGRaCmSG0oqtZB6qqHvw8rYFMT3DsZn34Ze+3M\ns9R+Np2H9wKBgQDluSI8NdhG/tY72KHfYnli2cv1odXKb2GLSSqd56HJwBVKVwHz\nuKxxFX9SQIt0Wp6kgiifXn6du2gvuKYtjZlpee0e2Q3o0kVdh2yzypMcg0xgLb1b\nP2sJYVnznwIq966EgFg9ie3ch+otg6Ffi7q+Ys1nq8wCng1i0hZDDJzmbQKBgE6p\nw88JG5P4h8O+/Tx811B4Z41g3DMLdLzyfK9Tx3kS9wIxvHMC0Ys0wVlAt9dDeccq\nCpeAEwefIT61SXirTAsl86/a80adNSzbC6CPt/ebWTUDNpKsiKvL9I/bChIlvkgs\nrOk/XePuhViMoRWGcmhaO4lrq4WdKLPDf7dNd2phAoGBAN11GAiGyeDxphgaEb55\n7KGqkYU0LqfMwnUJRchtBx+TPcObsFj46g1rf66R+ZCSngPSxX+fXPCZYaFd/pEA\nJgrdlOPvdQkdmOP0kSi6Xmytojr+5xoODdnvzWtr21jsCFxn3apHt4fs6tlfyhTS\ngymaIC2G9WG3WAEMw2A2i3m9\n-----END PRIVATE KEY-----\n
      DIALOG_FLOW_CLIENT_EMAIL: dialogflow-tqfcaw@claimbot-vxtlgn.iam.gserviceaccount.com
      DIALOG_FLOW_CLIENT_ID: 111476536459718875872
      GOOGLE_APPLICATION_CREDENTIALS: private_key.json
      CLAIM_REPOSITORY_HOST: http://claimrepository:8081
      GOOGLE_API_KEY: AIzaSyBuZXEcDehWONb3Np0axuAj0jg8l9K00pw
      OCR_FEATURE: 0

  # CLAIM SUBMISSION FRONTEND
  claimsubmissionfrontend:
    build: ./claimSubmission/frontend
    ports:
      - "5001:80"
    restart: always
    links: 
      - "claimsubmissionserver"
    environment: 
      API_HOST: http://127.0.0.1:5000
      DIALOGFLOW_AGENT_ID: f100c550-d81c-4f7f-952b-c2690d1c933f

  # DASHBOARD
  dashboard:
    build: ./dashboard
    ports:
      - "9001:80"
    restart: always
    environment: 
      CLAIM_REPOSITORY_HOST: http://127.0.0.1:8081
      CHATBOT_URL: http://127.0.0.1:5001
      
  # CLAIM CLASSIFICATION SERVICE
  claimclassification:
    build: ./claimClassification
    ports:
      - "9999:9999"
    restart: always
    links: 
      # - "claimrepository"
      - "eventdispatcher"
    environment: 
      CLAIM_REPOSITORY_HOST: http://claimrepository:8081
      EVENT_DISPATCHER_HOST: amqp://eventdispatcher
      HOST: 0.0.0.0
      PORT: 9999

  # CLAIM DISTRIBUTER SERVICE
  claimdistributer:
    build: ./claimDistributer
    ports:
      - "5003:5003"
    restart: always
    links: 
      - "claimrepository"
    environment: 
      CLAIM_REPOSITORY_HOST: http://claimrepository:8081
      HOST: 0.0.0.0
      PORT: 5003
volumes:
  eventdispatcher_data: {}
  db_data: {}  