export const ACTION_TYPES = {
    SET_DIALOG_FLOW_SESSION_ID: 'SET_DIALOG_FLOW_SESSION_ID',
    ADD_TO_DIALOG_FLOW_MESSAGE_QUEUE: 'ADD_TO_DIALOG_FLOW_MESSAGE_QUEUE',
    ADD_TOAST_MESSAGE: 'ADD_TOAST_MESSAGE',
    CLEAR_TOAST_MESSAGES: 'CLEAR_TOAST_MESSAGES'
}